### ISSUE TITLE
Implement marker + cluster map

### ISSUE THREAD

**Issue by samuelbeck** [InTaVia/web#104]
Or similar clustered map view.

![image](https://user-images.githubusercontent.com/13209213/199716381-596cf170-71de-4561-97b5-e1a0deb37406.png)

**Comment by johannesliem** [comment]
- [ ] cluster == false > simple marker
- [ ] cluster == true > donut cluster (segments event types)
- [ ] cluster == true > dot cluster

**Comment by johannesliem** [comment]
Currently we have a donut cluster layer and a dot cluster layer with a kind of spiral layout (which does not place evetns in a chronological order but puts them in a geometrical order) > ToDo: requires some solution to order them chonologically
