### ISSUE TITLE
[Dürer-Data]: Enrich CH objects with place information

### ISSUE THREAD

**Issue by samuelbeck** [InTaVia/web#136]
CHOs currently don't have places related to their creation events. For the workshops should enrich the objects with place information by either
(1) writing a script to extract the information from Dürer's events
(2) manually enriching the data by hand.

**Comment by johannesliem** [comment]
https://github.com/InTaVia/data-import/raw/main/public/data/data-duerer.xlsx

event-cho tab (cho creation events during nl journey) manually updated with most/a likely place (might require some corrections)
