### ISSUE TITLE
Cannot get Jest to run tests for the timeline page, which imports d3 ESM modules

### ISSUE THREAD

**Issue by mfranke93** [InTaVia/web#15]
Apparently, Jest has issues with ESM imports in some cases. I get the following (non-sensical) error message when trying to run Jest:

```
 FAIL  test/pages/timeline.page.test.tsx
  ● Test suite failed to run

    Must use import to load ES Module: /home/max/prog/InTaVia/node_modules/d3-array/src/index.js

    > 1 | import { extent } from 'd3-array';
        |                                  ^
      2 | import { scaleBand, scaleTime } from 'd3-scale';
      3 | import type { MutableRefObject } from 'react';
      4 | import { useEffect, useState } from 'react';

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:972:21)
      at Object.<anonymous> (src/features/timeline/TimelineSvg.tsx:1:34)
      at Object.<anonymous> (src/features/timeline/Timeline.tsx:8:62)
```

See also this [`d3-array` issue](https://github.com/d3/d3-array/issues/218), which was closed as "won't fix". See also [here](https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/) and [here](https://jestjs.io/docs/ecmascript-modules).

I'm not sure how to proceed, except for not writing any tests for the timeline for the time being.

**Comment by chriszrc** [comment]
@mfranke93 any chance you can explain the fix for the rest of us...
