### ISSUE TITLE
[Collection panel]: Error getTranslatedLabel

### ISSUE THREAD

**Issue by samuelbeck** [InTaVia/web#161]
Getting the following error when trying to expand an entity kind in the collection panel in the VAS:
![image](https://user-images.githubusercontent.com/13209213/223661550-72ca69b1-b04c-4495-96d9-2c63e4109973.png)

The error occurred with a collection that contained all Klimts, Ludwig van Beethoven, Ego Schiele, and Adalbert Stifter when I tried to expand the "persons" accordion.

**Comment by stefanprobst** [comment]
this happens because some related events don't return a label field, e.g.:

```

**Comment by samuelbeck** [comment]
Is this a backend issue or do we need to be able to handle this?

**Comment by stefanprobst** [comment]
definitely a backend/data issue - for now i did https://github.com/InTaVia/web/blob/dev/src/lib/get-translated-label.ts#L10-L12

**Comment by stefanprobst** [comment]
i guess we can close this.
