### ISSUE TITLE
Bringing the Ego-Network to SC and SV

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/web#238]
**Implementation Steps SC:**

- [x] add ego-network to visualizationTypes of SC
- [x] in SC write node-link structure to store? (which can be used for uploading to SV)

**Notes:**

- Network in SC does not render smooth bc. simulation triggers constant repaint of preview png (story flow); Any ideas how to solve?

**NodeLink Data Structure:**
```
export interface Node {
  id: Entity['id'];
  entity: Entity['id'];
  x: number;
  y: number;
  isPrimary: boolean;
}

export interface Link {
  source: Node['id'];
  target: Node['id'];
}
```

**Visualization State:**
- add nodeLinkStructure attribute to Visualization (visualization.slice.ts)
- networkEntities (array of entities that are linked to main entities) > to be seraialized to storyEntities when "uploading" story
- ...

**Viewer**
- use node link structure to create d3 network
- network & simulation: https://github.com/InTaVia/web/blob/a1b318096d6c31cdac9cb90ee4f87432fbe68d0c/src/features/ego-network/network.tsx#L62C1-L87C23

**Comment by samuelbeck** [comment]
Rework node and link data structures to reference entities and nodes by id only
