### ISSUE TITLE
GeoMap assumes that entities always have geometry

### ISSUE THREAD

**Issue by samuelbeck** [InTaVia/web#250]
This leads to the application crashing if it's not the case.

![image](https://github.com/InTaVia/web/assets/13209213/923a5e1f-07d7-4a71-9e68-e857999810dd)

**Comment by johannesliem** [comment]
Would you have an example detail page where this happens? Where place does not has a geom (or coordinates). Does the example from above relates to a place entity?

**Comment by samuelbeck** [comment]
The error occurred when Angel imported an [IDM-JSON file](https://gist.github.com/samuelbeck/7241c90ff7d267ba5f8e8263f2b644a1). Paris doesn't have geometry associated with it and the app crashes when opening its detail page.

We should probably just check whether geometry isn't undefined before using it.

**Comment by johannesliem** [comment]
Mhm ... looks like that the hasGeometry check does not work as expected...

const hasGeometry =
    useEntityHasGeometry(entity) || (entity.kind === 'place' && entity.geometry !== undefined);

**Comment by samuelbeck** [comment]
I found the error. In the knowledge graph places don't have any relations. Therefore, `useEntityHasGeometry(entity)` always returns `false`. However, as in this case, in Angels data places can have relations to other entities. If these entities have geometry the hook will return true and the map will get rendered.

This isn't a problem by itself. However, because until know we didn't expect places to have relations, we tread them differently from other entity kinds when it comes to the map. Instead of rendering the events on the map we render a marker at the coordinates of the geometry object. Since Paris doesn't have a geometry object in this case but `useEntityHasGeometry(entity)` returns true the map is rendered without any geometry being passed to the component.

I will fix the error in the entity-details component but it probably still makes sense to check in the GeoMap component whether an entity actually has a valid geometry before passing it to the map.

**Comment by johannesliem** [comment]
In the geomapwrapper component only events that have related places with valid geometries are used in the layers of the geomap. As you said, the geomap as used for places on the entity detail page is different; I think as for the example, it is the initialViewState(lat, lon) and the Marker positon (lat, lon) that would require a check. While we could check for the viewstate in the geomap and use default values otherwise; we would need to check outside of the react-map-gl marker component - as we do already.

**Comment by johannesliem** [comment]
I will have a look, thanks for fixing and documenting.
