### ISSUE TITLE
Search always returns 404 (Not Found), none of the pages work (Chromium)

### ISSUE THREAD

**Issue by mfranke93** [InTaVia/web#51]
Starting the server with `npm run dev` and opening `localhost:3000` in a Chromium browser (QtWebEngine 5.15.9, based on Chromium 87.0.4280.144), search always returns 404, and the "Rejected" popup appears.

I also get the error that the manifest is not found, which might relate to #50:
```
GET http://localhost:3000/site.webmanifest 404 (Not Found)
```

**Comment by stefanprobst** [comment]
hmm just tried the following, and everything's working fine:

```bash
git clone git@github.com:intavia/web
cd web
npm i
npm run dev
```

**Comment by samuelbeck** [comment]
I'm getting the same error message as Max in Edge and Firefox on the dev branch when searching.

**Comment by stefanprobst** [comment]
please try running `npx msw init public`

**Comment by stefanprobst** [comment]
for context: https://github.com/mswjs/msw/discussions/1015#discussioncomment-1747585

service worker script is now gitignored but should be autogenerated on package install.

going to add npm script for manual install

**Comment by mfranke93** [comment]
> hmm just tried the following, and everything's working fine:
> 
> ```shell
> git clone git@github.com:intavia/web
> cd web
> npm i
> npm run dev
> ```

Interesting. This now works for me, flawlessly both in Firefox (#50) and in Chromium.

> service worker script is now gitignored but should be autogenerated on package install.

Yesterday, I did a

```
git pull
npm i
npm run dev
```

which should have run the `prepare` script as well. But it seems a fresh repository does something different.

**Comment by samuelbeck** [comment]
Apparently the service worker script is only auto-generated at package install. That's why it didn't re-generate it when you ran `npm i` in the existing repo.

**Comment by stefanprobst** [comment]
just added script to manually regenerate service worker with `npm run generate:msw`

**Comment by mfranke93** [comment]
> That's why it didn't re-generate it when you ran `npm i` in the existing repo.

Maybe the `generate:msw` and the `generate:favicons` scripts (I get favicon 404s on the old install as well) should be run as part of the `prepare` script then. That runs on *every* `npm install`.

Otherwise, if it now works for @samuelbeck on Edge and Firefox as well, I guess this and #50 can be resolved.

**Comment by stefanprobst** [comment]
the `generate:favicons` script currently runs in `prebuild` because i didn't think we'd need to have favicons in dev, but i'm fine with changing

**Comment by mfranke93** [comment]
I agree that the favicons are not essential. But there should be an easier way to get a cloned repository to a "fresh" state that deleting and re-cloning it. I guess just running `npm run generate` would do that *now,* but what if in the future there are other stateful changes introduced into the build? Already now, there are a lot of npm scripts, and especially for me as an infrequent contributor, it is really hard to determine what they do and when they are called. Maybe the scripts could be briefly documented, for example in the README.
